### ISSUE TITLE
true value should convert to string...

### ISSUE THREAD

**Issue by jmervine** [heroku/loggerator#7]
Thinking that something like

```
log(foo: :bar, success: true)
```

Should log `foo=bar success=true`, but currently logs `foo=bar success`.

@reidmix thoughts?

**Comment by reidmix** [comment]
yup that's a pliny-ism: 
```ruby
if v == nil 
  nil
elsif v == true
   k
elsif  ... end
```

**Comment by jmervine** [comment]
The resolution to this would be removing [this](https://github.com/heroku/loggerator/blob/master/lib/loggerator/log.rb#L70-L71) `if` check so that the `else` takes over and converts `true` to a string.

**Comment by blackfist** [comment]
I would prefer to log `success=true` rather than just success because then it's easy to splunk for the success cases.  If I were looking for only successful authentication logs I would rather splunk for `authenticated=true` rather than `authenticated NOT authenticated=false`
